apiVersion: v1
kind: Service
metadata:
  name: spring-petclinic-service
spec:
  type: NodePort
  selector:
    app: spring-petclinic
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30007
